---


- name: Create "docker" group
  group:
    name: "{{ docker_group }}"
    state: present

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    group: "{{ docker_group }}"
    append: yes
  notify: "start docker on boot"
